### PR TITLE
css to handle safe area on mobile landscape mode

### PR DESCRIPTION
**Pull request by Raulkg**
- Implemented protection from safe areas in extra device space in landscape mode especially for iPhone devices
- Increased accessible area to accommodate touch or click events on the menu. A known issue of safari in landscape full-screen mode is sometimes unresponsive.
- view-port settings according to zoom level
- Implemented performance improvements by prefetching stylesheets  (improved lighthouse score)

### CODE REVIEW

**Review by jeffswartz — CHANGES_REQUESTED** [review]
Not sure what's going on, but the subscriber buttons (which we are trying to fix in ECO-5596) are not being displayed on my iPhone X:

image

**Comment by Raulkg** [comment]
> Not sure what's going on, but the subscriber buttons (which we are trying to fix in ECO-5596) are not being displayed on my iPhone X:
> 
> image
> 
> (See the gray oval in the upper-left corner of the subscriber. It is missing the audio and video control buttons.)

 1) are you using safari or chrome?
2) is it iPhone XR ?

**Review by jeffswartz — APPROVED** [review]

**Comment by jeffswartz** [comment]
> > Not sure what's going on, but the subscriber buttons (which we are trying to fix in ECO-5596) are not being displayed on my iPhone X:
> > image
> > (See the gray oval in the upper-left corner of the subscriber. It is missing the audio and video control buttons.)
> 
> 1. are you using safari or chrome?
> 2. is it iPhone XR ?

It's an iPhone Xs, but I cannot reproduce this issue now. I'll keep an eye on it.

**Comment by jeffswartz** [comment]
Now that I can see the subscriber control buttons on the iPhone, they still do not work as expected. Sometimes (about half the time), clicking the mute audio or mute video button for a subscriber results in the bottom controls being displayed. Then (about half the time) the buttons work as expected.

**Pull request merged**
