### PR TITLE
Fix network test console logging

### PR DESCRIPTION
**Pull request by jeffswartz**

### CODE REVIEW

**Review by emilianop11 — COMMENTED** [review]
Vonage_Video_Conferencing

Im getting this error. Would you say its also related to precall test?

**Comment by jeffswartz** [comment]
> Vonage_Video_Conferencing
> 
> Im getting this error. Would you say its also related to precall test?

I cannot reproduce this. What browser are you using? Have you set the precallTest config settings?

**Comment by emilianop11** [comment]
the errors above were due to missing config. my bad.
now after including the missing config im consistently getting
Vonage_Video_Conferencing

im on chrome 86

**Comment by jeffswartz** [comment]
> the errors above were due to missing config. my bad.
> now after including the missing config im consistently getting
> Vonage_Video_Conferencing
> 
> im on chrome 86

It appears that OpenTok.js does not always behave gracefully when you call `Session.disconnect()` or `Session.unpublish()` before a Publisher has completed establishing a PeerConnection or attaching the video to the DOM. Anyway, this PR works around some of the race conditions, but not all of them. In general, if the end-user does not click "Join Meeting" right away, then there will be no errors logged in the console.

If the code in this PR looks good and it fixes some timing errors, please go ahead and approve it, @emilianop11 . We can look into the other logging issues later. Thanks.

**Review by emilianop11 — APPROVED** [review]

**Pull request merged**
