### PR TITLE
ECO-5687 - Remove support for IE

### PR DESCRIPTION
**Pull request by jeffswartz**
Note that the OTHelper.js file already calls `OT.upgradeSystemRequirements()`, which displays a dialog box saying the app is not supported. I think that suffices for now. We can discuss other UI options with Design.

### CODE REVIEW

**Review by Raulkg — COMMENTED** [review]
OtHelper throws error. - "Unsupported browser, probably needs upgrade" . If this is the same message that is displayed to the user, I prefer a more specific message saying IE or Edge browsers are not supported at the moment in case that is a feasible solution

**Comment by jeffswartz** [comment]
> OtHelper throws error. - "Unsupported browser, probably needs upgrade" . If this is the same message that is displayed to the user, I prefer a more specific message saying IE or Edge browsers are not supported at the moment in case that is a feasible solution

No. This string is not displayed to the user (or really used at all).

**Review by Raulkg — APPROVED** [review]
LGTM

**Review by emilianop11 — APPROVED** [review]
LGTM!!!

**Pull request merged**
